### ISSUE TITLE
Add Flare as obstacle to dataset generation

### ISSUE THREAD

**Issue by niemiaszek** [knr-auv/simulation#17]
[enhancement][dataset generation]
Add flare model now as obstacle, in future used as object for detection
Example of flare left to the gate:
![flare](https://user-images.githubusercontent.com/46727980/101392788-7571bb80-38c6-11eb-9ed0-8f10610e2ab4.png)

**Comment by VECTR0** [comment]
Flares added in v. 2.1.1
