### ISSUE TITLE
Labeling objects with invisible flag

### ISSUE THREAD

**Issue by niemiaszek** [knr-auv/simulation#20]
[bug, dataset generation]
Objects with false v flag still get generated label in txt. Only happens for objects in the "gate" class, for "multiple" detection labels are not generated.

Example: 
![2](https://user-images.githubusercontent.com/46727980/102424512-92676680-400b-11eb-871e-21dd3e7cb02e.png)
[2.txt](https://github.com/knr-auv/simulation/files/5706337/2.txt)

**Comment by VECTR0** [comment]
Fixed in b8fdf2d4490de5f544f08b81040ab0c97a85609d and added parameter `[f]ogDensity` int debug rect for more debugging.
