### ISSUE TITLE
Visibility not always detemined well

### ISSUE THREAD

**Issue by niemiaszek** [knr-auv/simulation#21]
[bug, dataset generation]
Sometimes visible objects are set as invisible, other times it's reversed.
Invisible object labeled as a visible example:
![16](https://user-images.githubusercontent.com/46727980/102425274-43bacc00-400d-11eb-8f39-7b54a1d91e64.png)

Visible object labeled as an invisible (one of four gates not labeled, even tho they have all true and positive v and i flags and minfill):
[1.txt](https://github.com/knr-auv/simulation/files/5706377/1.txt)
![1](https://user-images.githubusercontent.com/46727980/102425475-af9d3480-400d-11eb-8c8e-9e2b838c98cf.png)

**Comment by VECTR0** [comment]
What are the settings for minfill?

**Comment by niemiaszek** [comment]
minObjectFill: 0.01499999989
  minObjectColorPercentVisible: 0.149999997

**Comment by niemiaszek** [comment]
More examples as requested
![4](https://user-images.githubusercontent.com/46727980/102689447-7aa40400-41fe-11eb-946e-a9c545b8c161.png)
[4.txt](https://github.com/knr-auv/simulation/files/5719399/4.txt)


![2](https://user-images.githubusercontent.com/46727980/102689434-5e07cc00-41fe-11eb-931e-b4381c16defb.png)
[2.txt](https://github.com/knr-auv/simulation/files/5719398/2.txt)

**Comment by VECTR0** [comment]
Ok, I will close this issue for now and send a new dev-build because b8fdf2d4490de5f544f08b81040ab0c97a85609d probably solved this issue and your debug rects can't be trusted #20
