### ISSUE TITLE
Fix needed for visability of objects 

### ISSUE THREAD

**Issue by niemiaszek** [knr-auv/simulation#6]
[dataset generation]
New requirement for visiability of objects needed. Sample images showing the issue:
Picture 1- gate with 1,18% of frame, 17m distance, not visible
Pictures 2 and 3 - gate closer, % of frame lower, visible
I think there is connection with light intensity, for sure with the distance and how it affects object appearance through fog
![4](https://user-images.githubusercontent.com/46727980/93004021-b49ca480-f543-11ea-8dfa-423fe770ecd7.png)
![7](https://user-images.githubusercontent.com/46727980/93004003-9e8ee400-f543-11ea-8ea1-76ac1794c61b.png)
![102](https://user-images.githubusercontent.com/46727980/93004102-3a205480-f544-11ea-97a2-09c7dfd57265.png)

**Comment by VECTR0** [comment]
Added new parameter to check if visible in fog.
