### ISSUE TITLE
More accurate blank dataset needed

### ISSUE THREAD

**Issue by niemiaszek** [knr-auv/simulation#7]
[enhancement][dataset generation]
Higher variety of not-object dataset is needed to prevent false positives. I suggest adding model of OKOŃ and some human models to the generated dataset (both pictures with gate and blank pictures). It also might be the issue related to #6  
sample video for showing the issue: [wynikop9_fp](https://drive.google.com/file/d/1XwQlE4BwaCrWoPFRB5IFssOKvqqcKkW5/view?usp=sharing)

**Comment by VECTR0** [comment]
Added new class for objects that are not included in dataset, but they exist during generation as obstacles.
